### ISSUE TITLE
建议：SmartZip.ini编码修改

### ISSUE THREAD

**Issue by ivysrono** [vvyoko/SmartZip#1]
目前生成的SmartZip.ini默认编码是GB2312，vscode打开默认乱码。
建议调整为UTF-8编码。

**Comment by vvyoko** [comment]
ini只支持 utf-16
https://wyagd001.github.io/v2/docs/commands/IniWrite.htm#Remarks

如果你会ahk v2的话可以试试以下代码
它先生成一个utf-8的ini文件,然后在其中写中中文
```
FileEncoding("UTF-8")
FileAppend("a",  "ini.ini")
IniWrite("用7-Zip打开", "ini.ini", "menu", "openZipName")
```
结果会是这样
![20220615125724](https://user-images.githubusercontent.com/2145741/173739828-dedb8613-9fcb-4c16-82e3-b25a34c9c104.jpg)
