### ISSUE TITLE
作者你好，想问一下，怎么用正则表达式改名后缀为7z.0删01.7z.0删02.类的分卷压缩包，并且解压的

### ISSUE THREAD

**Issue by wzgrx** [vvyoko/SmartZip#13]

**Comment by wzgrx** [comment]
在网上没有搜到^[ 	]+<--->这种表达式的说明

**Comment by vvyoko** [comment]
将这个添加到改名后缀名中
`0删<--->0`
但除非大量碰到,否则还是建议手动改名

`<--->`是分隔符
左边是搜索项,右边是替换项
你发的示例就是替换`^[ ]+`为空
当初没有专精这个只是粗略写了写
这个是替换空白为空,写成这样你可以能看明白
`^\s+` 就是去除文件名开头的空白.

最近在忙另外一个项目
https://github.com/vvyoko/EditRename
到时可以会把`<--->`改成`;`
但意思是一样的

**Comment by wzgrx** [comment]
> 将这个添加到改名后缀名中 `0删<--->0` 但除非大量碰到,否则还是建议手动改名
> 
> `<--->`是分隔符 左边是搜索项,右边是替换项 你发的示例就是替换`^[ ]+`为空 当初没有专精这个只是粗略写了写 这个是替换空白为空,写成这样你可以能看明白 `^\s+` 就是去除文件名开头的空白.
> 
> 最近在忙另外一个项目 https://github.com/vvyoko/EditRename 到时可以会把`<--->`改成`;` 但意思是一样的

好的，非常感谢，软件非常好用

**Comment by wzgrx** [comment]
解压.7z.0删01
解压.7z.0删02
解压.7z.0删03
测试解压上面文件，解压失败，后缀名规则和密码都没有问题，0删<--->0，用管理员权限也没反应，是不是不支持改后缀名后再解压？

ini设置
[set]
zipDir=D:\Soft\7-Zip
icon=%SmartZipDir%\SmartZip.exe
nesting=1
nestingMuilt=1
partSkip=0
delSource=1
delWhenHasPass=0
autoAddPass=1
dynamicPassSort=1
autoRemovePass=0
targetDir=
test=1
successPercent=90
logLevel=5
cmdLog=1
hideRunSize=10
addDir2Pass=0
[password]
1=解压
[menu]
openZipName=用7-Zip打开
unZipName=智能解压
unZipCPName=手动指定代码页解压
addZipName=压缩
[ext]
1=zip
2=rar
3=7z
4=001
5=cab
6=bz2
7=gz
8=gzip
9=tar
[extExp]
1=^\d+$
2=zi
3=7
4=z
[extForOpen]
1=iso
2=apk
3=wim
4=exe
[renameExt]
1=mp+3<--->mp3
2=0删<--->0
[renameName]
1=666666<--->
[renameExp]
1=^[ 	]+<--->
2=[ 	]+$<--->
[excludeExt]
1=
[excludeName]
1=
[deleteExp]
1=
[7z]
openAdd=.zip" -tzip -mx=0 -aou -ad
add=.zip"
[unZipCheckError]
1=Wrong password<--->1
2=Cannot open encrypted archive<--->1
3=No files to process<--->1
4=ERROR:<--->10
[unZipCheckErrorExp]
1=
[unZipCheckSuccess]
1=Everything is Ok<--->1
[unZipCheckSuccessExp]
1=
[openZipCheckError]
1=Errors: 1<--->1
2=ERROR:<--->1
[openZipCheckErrorExp]
1=
[openZipCheckSuccess]
1=Enter password (will not be echoed):<--->1
[openZipCheckSuccessExp]
1=\d*-\d*-\d* *\d*:\d*:\d* *\d* *\d* *(\d*) files(, (\d*) folders)?<--->1
[temp]
version=20
[passwordSort]
1=0

log
#####
D:\Soft\7-Zip\7z.exe l -slt -bsp1  "E:\新建文件夹_20220501_172839\解压.7z.0删02"
[1] 
[2] 7-Zip 22.01 (x64) : Copyright (c) 1999-2022 Igor Pavlov : 2022-07-15
[3] 
[4] Scanning the drive for archives:
[5]   0M Scan E:\新建文件夹_20220501_172839\
[6]                                               
[7] 1 file, 4697620480 bytes (4480 MiB)
[8] 
[9] Listing archive: E:\新建文件夹_20220501_172839\解压.7z.0删02
[10] 
[11] 
[12] Errors: 1

**Comment by vvyoko** [comment]
刚看了下...
后缀名是完全匹配的.
当初的想法应该是防止误操作把不该改的改了...

应该是把上面说添加到 `改名文件名`中
简单限制到后缀名中可以这样
` .0删<--->.0`

再一步可以这样限制,添加到`改名正则`中
`\.0删(\d+$)<--->.0$1`

**Comment by wzgrx** [comment]
> .0删<--->.0



> 刚看了下... 后缀名是完全匹配的. 当初的想法应该是防止误操作把不该改的改了...
> 
> 应该是把上面说添加到 `改名文件名`中 简单限制到后缀名中可以这样 ` .0删<--->.0`
> 
> 再一步可以这样限制,添加到`改名正则`中 `\.0删(\d+$)<--->.0$1`

都试了一下，都不行，是不是因为电脑是win11的关系
报错
Error: This value of type "String" has no method named "Call".

▶	801: If A_TickCount - timeSave < 50 || wParam != 6 || !WinExist(sub())

Call stack:
*#1 (801) : [ShellMessage] If A_TickCount - timeSave < 50 || wParam != 6 || !WinExist(sub())
> OnMessage

**Comment by vvyoko** [comment]
这是界面的报错,只有批量解压时才会出现
我本地测试了没有问题...
现在本项目已处于搁置状态了
属于是能用就用,不能用也没办法的状态...
就是因为是调用第三方所以有很多问题靠我是无法解决的(不包括你说的这个)
所以渐渐也闲鱼了....

**Comment by wzgrx** [comment]
> 这是界面的报错,只有批量解压时才会出现 我本地测试了没有问题... 现在本项目已处于搁置状态了 属于是能用就用,不能用也没办法的状态... 就是因为是调用第三方所以有很多问题靠我是无法解决的(不包括你说的这个) 所以渐渐也闲鱼了....

好的，辛苦了
