### ISSUE TITLE
建议增加自定义解压目录

### ISSUE THREAD

**Issue by chibuhu** [vvyoko/SmartZip#3]
建议增加可以在配置里自定义解压目录

**Comment by vvyoko** [comment]
正好准备发布新版

已经实现
在`targetDir`设置

这个只用于解压,我不确定这是否要用于压缩?
压缩在当前目录生成这是件很直观的事吧...

**Comment by chibuhu** [comment]
压缩是在当前目录，解压可以指定目录，很好用

**Comment by teteko233** [comment]
@vvyoko 希望支持命令行解压参数 -destination 之类的。另外，如果可以在命令行指定密码参数 -password 就好了

**Comment by vvyoko** [comment]
> @vvyoko 希望支持命令行解压参数 -destination 之类的。另外，如果可以在命令行指定密码参数 -password 就好了

这其实不是个命令行程序....
所以它并不像其他命令行程序自带了这种参数解析
目前此项目已经搁置,更加..
