### ISSUE TITLE
额外的解压报错

### ISSUE THREAD

**Issue by ivysrono** [vvyoko/SmartZip#5]
2.21，没有修改任何参数，智能解压[doublecmd-1.0.6.x86_64-win64.zip](http://sourceforge.net/projects/doublecmd/files/DC%20for%20Windows%2064%20bit/Double%20Commander%201.0.6%20beta/doublecmd-1.0.6.x86_64-win64.zip/download)出现错误：

![图片](https://user-images.githubusercontent.com/2649544/174323956-0d1f2972-79ce-457d-b36e-1c62bad106b7.png)

直接用7-zip解压没有错误。

**Comment by vvyoko** [comment]
我的原因...
在2.20的时候我在选项中新增了 `test` 选项
这个的用处是测试 替代 CheckErrorContinueExp 检查文件错误的...

测试的时候我把这个功能注释掉了(禁用)
测试完成忘了把这个改回来
测试功能默认是关闭的
我自己为了测试开启这个功能
导致普通用户既没有test功能,也没原版的功能.....

就是下面这一行...

[                ; this.IniReadLoop(what "CheckErrorContinueExp", checkSave.errorrContinueExp, , true)
](https://github.com/vvyoko/SmartZip/blob/d724b266a626f1030f6dd2e5257df635a80f53eb/SmartZip.ahk#L1011)


目前可在选项中改 `set`-`test` 为 1
或者等我发布新版.

**Comment by vvyoko** [comment]
你可以测试下 [2.21fix](https://github.com/vvyoko/SmartZip/releases/tag/2.22)
看看是否工作正常

**Comment by ivysrono** [comment]
fixed

**Comment by ivysrono** [comment]
fixed
