### ISSUE TITLE
智能解压的判断逻辑存在过度解压的可能

### ISSUE THREAD

**Issue by Dyannna** [vvyoko/SmartZip#6]
复现步骤：
1. 下载 https://github.com/IrineSistiana/mosdns/rele3ases/download/v4.0.0-alpha2/mosdns-freebsd-amd64.zip
2. 对得到的压缩包通过右键菜单执行智能解压操作
3. 可通过7zip的窗口观察到其中包含的可执行文件mosdns也被解压了。

查看代码，应该与 
https://github.com/vvyoko/SmartZip/blob/main/SmartZip.ahk#L263
https://github.com/vvyoko/SmartZip/blob/main/SmartZip.ahk#L946 
处将无扩展名文件尝试进行嵌套解压有关。鉴于整理所有可解压的文件格式可能需要消耗大量精力以及使耗时进一步增加，希望能够提供不进行嵌套解压的选项。

**Comment by vvyoko** [comment]
此脚本原本是因为各种防和谐手段才做的
具体包括修改后缀名,嵌套等等....

所以最开始会有各种难以理解的东西
比方说为什么要判断每个文件是否是压缩包...
为什么遍历不是压缩包的格式...

也包括你说的这个没后缀名的...

新版会提供选项关闭嵌套解压
