### ISSUE TITLE
请求支持 7z 变体 Nanazip

### ISSUE THREAD

**Issue by txyyh** [vvyoko/SmartZip#7]
[Nanazip](https://github.com/M2Team/NanaZip) 是一个著名的 Windows 7-zip 变体，安装时会向系统添加 Path，只提供 msix 安装方式

其命令行接口程序 NanaZipC.exe 与 7z.exe 功能一致，直接修改调用应该就能完成适配

**Comment by vvyoko** [comment]
我关注了Nanazip但没使用..
我目前还在WIN10没有右键方面的烦恼(我连7zip的右键都不用...)
其他的好像都是界面方面的修改,对我吸引力不是很大...

https://github.com/vvyoko/SmartZip/blob/9e523d07e7df758709c10e5862f544192e98ba7e/SmartZip.ahk#L45
https://github.com/vvyoko/SmartZip/blob/9e523d07e7df758709c10e5862f544192e98ba7e/SmartZip.ahk#L46
https://github.com/vvyoko/SmartZip/blob/9e523d07e7df758709c10e5862f544192e98ba7e/SmartZip.ahk#L47

45-47行把 `7z.exe` 等改成对应的看看能不能运行
估计可能会出问题
像SmartZip这种工作于特定软件的东西我是不大想追求兼容其他的
开源嘛,好的一点就是有能力就可以自己改改
不然就只能别人提供什么就用什么了....

**Comment by txyyh** [comment]
主要他同时合了zstd和nsis俩分支的代码，能走store更新，其他我觉得有用的还在roadmap

> 开源嘛,好的一点就是有能力就可以自己改改
不然就只能别人提供什么就用什么了....

但我觉得能提还是提一下为好，issue也是一种贡献吧（
我现在自己也是因为本项目还在7z-zstd，毕竟原版也不是完全不支持nsis

**Comment by vvyoko** [comment]
首先明确回复一下吧.
不会去兼容...

接受此前提的情况下也很欢迎继续讨论.
7-Zip-zstd 的版本是兼容的
我以前就是用的
https://github.com/mcmilk/7-Zip-zstd
不过它不更新了所以换到了官方版本

刚去测试了一下,目前NanaZip是能运行的.
设置7zip目录为NanaZip所在目录
然后修改我上面说的为这样
```
        this.7z := sevenZipDir "\NanaZipC.exe"
        this.7zG := sevenZipDir "\NanaZipG.exe"
        this.7zFM := sevenZipDir "\NanaZip.exe"
```
大部分功能(压缩,解压包含密码的文件)是正常的
更详细的就没测试了

此脚本是基于AHK并且很多部分是写死的.(7zip历史很悠久且不轻易更改)
受限于AHK,不加入外部库的情况下只能读取很古老的界面(winfrom)
界面越先进越不能读取.比方说wpf,QT等等....
也就是NanaZip越优化,离兼容就越远(这不是缺点)....

所以你不妨照着我说的修改尝试是否能够正常工作
出现问题可以接着询问.
