### ISSUE TITLE
解压过程报错

### ISSUE THREAD

**Issue by Smile8848** [vvyoko/SmartZip#8]
![](http://pic.rmb.bdstatic.com/bjh/8c48b3a51847748689b607fc2e78ac12.png)
![](http://pic.rmb.bdstatic.com/bjh/d0e71d619be2cf74477176017b3177aa.png)

**Comment by vvyoko** [comment]
每次都会碰到这种情况吗

**Comment by Smile8848** [comment]
> 每次都会碰到这种情况吗

单个的时候不会 多个文件会发生

**Comment by vvyoko** [comment]
> > 每次都会碰到这种情况吗
> 
> 单个的时候不会 多个文件会发生

嗯,我知道是多个文件
这是界面部分的代码,单个文件是没有界面的

这行代码我都不知道怎么可能会出BUG...
所以才问是不是每次(解压多个文件)都会出错,
如果最新版本还一直抱这个错可能把 exe打包上传到评论里我测试一下

打包后拖拽到回复框里就可以上传

**Comment by Smile8848** [comment]
[SmartZip.zip](https://github.com/vvyoko/SmartZip/files/9250251/SmartZip.zip)
不知道为什么还是会报错

**Comment by Smile8848** [comment]
我是拖到界面解压的

**Comment by Smile8848** [comment]
解决了。。注册到右键不会发生。。不过右键菜单为什么不能只注册自动解压，注册出来是7z打开

**Comment by vvyoko** [comment]
> 我是拖到界面解压的

刚测试也没问题
但效果和右键解压不同
应该是哪部分有问题(和你说的问题无关)

拖到界面上解压是凑合的..
主要是让人体验下效果
主要功能里还要添加一部分代码去处理这个
效果并不太好,也没详细的测试过
更新日志上提到了准备删除这部分的功能

建议你别拖到主界面上
使用右键或者直接拖拽文件到`SmartZip.exe`的图标上
如果没问题就是使用右键的方式
如果还有错误可以尝试附件的这个

[SmartZip.zip](https://github.com/vvyoko/SmartZip/files/9250612/SmartZip.zip)

如果还是不行我也没啥好办法了.
这种看上去完全没问题的代码出现错误我是真不知道从哪修...
感觉就是 1+1=2 然后报错了一样...

**Comment by vvyoko** [comment]
> 解决了。。注册到右键不会发生。。不过右键菜单为什么不能只注册自动解压，注册出来是7z打开

好像也有其他人碰到这样的问题
把配置文件改名备份然后让其重新生成看看.
生成后可手动导入旧版的密码

顺便看看这个界面和我这是不是一样的
红框的这个是解压
![20220803185449](https://user-images.githubusercontent.com/2145741/182591611-87bada41-9107-4ea4-b9e0-0e42ae287e9d.jpg)

**Comment by Smile8848** [comment]
![QQ图片20220803185819](https://user-images.githubusercontent.com/31927778/182592214-81c2de60-403a-4db5-9125-69c587fb2e35.png)
![QQ图片20220803185947](https://user-images.githubusercontent.com/31927778/182592469-bab34b16-0a89-4d4c-8507-b42e3949aa21.png)
貌似还是如此，不过没关系注册到发送到用就好了 主要用不到其他选项有点占位置

**Comment by vvyoko** [comment]
> ![QQ图片20220803185819](https://user-images.githubusercontent.com/31927778/182592214-81c2de60-403a-4db5-9125-69c587fb2e35.png) ![QQ图片20220803185947](https://user-images.githubusercontent.com/31927778/182592469-bab34b16-0a89-4d4c-8507-b42e3949aa21.png) 貌似还是如此，不过没关系注册到发送到用就好了 主要用不到其他选项有点占位置

刚看了下是有问题
我把用7zip和智能解压的位置弄错了
我自己一直没用过导致没注意
最开始有人反应我还没在意...

这是第二次有人反馈了.
稍后更新

**Comment by vvyoko** [comment]
> 貌似还是如此，不过没关系注册到发送到用就好了 主要用不到其他选项有点占位置

可以试下新版修复了没有

**Comment by Smile8848** [comment]
> > ![QQ图片20220803185819](https://user-images.githubusercontent.com/31927778/182592214-81c2de60-403a-4db5-9125-69c587fb2e35.png) ![QQ图片20220803185947](https://user-images.githubusercontent.com/31927778/182592469-bab34b16-0a89-4d4c-8507-b42e3949aa21.png) 貌似还是如此，不过没关系注册到发送到用就好了 主要用不到其他选项有点占位置
> 
> 刚看了下是有问题 我把用7zip和智能解压的位置弄错了 我自己一直没用过导致没注意 最开始有人反应我还没在意...
> 
> 这是第二次有人反馈了. 稍后更新

感谢 实测修复了。
