### ISSUE TITLE
程序在某个情况下无法自动进行

### ISSUE THREAD

**Issue by absentmemory** [vvyoko/SmartZip#9]
一个双层压缩的压缩包，内外层都设置为7z，但是把外层的后缀改成别的（比如直接删掉后缀），通过7zip自带解压或者智能解压都会提示：
“无法作为[zip]压缩包打开该文件
文件以[7z]格式打开” 
导致内层的压缩包不会自动解压，需要在外层解压完成后点一下关闭才会继续进行内层解压。

**Comment by vvyoko** [comment]
我知道有这种情况,但没办法解决...

我逛的一个网站专门发这种
它那是把rar格式改成gz的.

曾经想过解决这个问题,也有思路

开启测试日志,解压这样的文件后打开日志察看会有这样的内容
```
[12] Path = G:\#aria2\041.gz
[13] Open WARNING: Cannot open the file as [gzip] archive
[14] Type = Rar5
```

7z能检测出是Rar5的文件
这应该是7zip的问题,它能检测其内容格式,但它还是以后缀名为准...
把其当作gzip文件打开然后出现错误
尝试过搜索是否有指定格式解压的命令行,没找到
甚至搜索过是否有忽略错误继续的命令行,也没找到.

然后想的检测出这个type的值
然后根据值的内容改文件后缀名
但这太复杂了,脚本完全没考虑过这样的情况
而且这个type的值有很多种,准确性我也没详细检测试过
最后搁置了

我自己目前是手动改后缀名

旧版遇见这种错误都不会弹出,导致卡在那里也不知道
最新版能粗略检测这种错误然后弹出

遇到不多就手动点下关闭吧
遇见很多只能像我这样先改后缀名了

**Comment by absentmemory** [comment]
好的，感谢回复
